name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      HOST: localhost
      PORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
      
    - name: Create-DB
      run: docker compose up -d --wait postgres

    - name: Test
      run: go test -v .
      
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - name: Build
      run: go build -v .

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: programa
        path: main
        
   
              

  docker:
    needs: build
    uses: ./.github/workflows/Docker.yml
    secrets: inherit
